# Generated by Django 2.2.1 on 2019-05-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sort_title',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
